### ISSUE TITLE
css box-sizing rule

### ISSUE THREAD

**Issue by trepmag** [ozdemirburak/jquery-floating-social-share#4]
Hello,

I've got a css issue while integrating you library because it define the following rule (https://github.com/ozdemirburak/jquery-floating-social-share/blob/master/src/jquery.floating-social-share.css#L8):
```
* {
    box-sizing: border-box;
}
```

I was required to override that; i couldn't notice it was necessary?

PS: thanks for sharing your library.

**Comment by ozdemirburak** [comment]
@trepmag First of all, sorry for this late reply.

Actually, it's not necessary and bad to have such global rule there, I don't even remember why I've added that. But after checking this on firefox, removing that ended up with uglier box style. Can you remove that and override the rules below and attach a screenshot?

```css
#floatingSocialShare a {
    height: 30px;
    line-height: 20px;
    padding: 8px 0;
}
```
